version: '3'

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "8699:8699"
    environment:
      - PORT=8699
      - NODE_ENV=development
    restart: unless-stopped
    container_name: planning-poker-backend

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "8600:80"
    depends_on:
      - backend
    restart: unless-stopped
    container_name: planning-poker-frontend

