version: '3'

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8699:8699"
    environment:
      - PORT=8699
      - NODE_ENV=development
    restart: unless-stopped
    container_name: planning-poker-backend

