name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get Git SHA for tagging
        id: git_sha
        run: echo "SHA_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: ./Backend
          file: ./Backend/Dockerfile
          push: true
          tags: |
            dilmand/planningpoker-backend:latest
            dilmand/planningpoker-backend:${{ steps.git_sha.outputs.SHA_SHORT }}

      - name: Build and push Frontend Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./Frontend
          file: ./Frontend/Dockerfile
          push: true
          tags: |
            dilmand/planningpoker-frontend:latest
            dilmand/planningpoker-frontend:${{ steps.git_sha.outputs.SHA_SHORT }}

  deploy:
    runs-on: self-hosted
    needs: build-and-push
    steps:
      - name: Deploy to Self-Hosted Runner
        run: |
          DEPLOY_PATH="/home/gruppe6" 

          cd "$DEPLOY_PATH" || { echo "Error: Directory $DEPLOY_PATH not found."; exit 1; }
          echo "Changed to directory: $DEPLOY_PATH"
          docker-compose pull || { echo "Error: Failed to pull Docker images."; exit 1; }
          docker-compose down || { echo "Error: Failed to stop services."; exit 1; }
          docker-compose up -d || { echo "Error: Failed to restart services."; exit 1; }

          docker image prune -f
          echo "--- Deployment Complete ---"
