name: Deployment

on:
  push:
    branches:
      - actions

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Deploy
        run: |
          # Pull the latest code
          cd ~/planningpoker
          git pull origin actions
          echo "Pulled latest code from the actions branch." 