name: Deployment

on:
  push:
    branches:
      - actions

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy
        run: |
          # Pull the latest code
          cd ~/code
          git pull origin actions
          echo "Pulled latest code from the actions branch." 